// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package checkin

import (
	"backend/api/checkin"
)

type ControllerV1 struct{}

func NewV1() checkin.ICheckinV1 {
	return &ControllerV1{}
}
