// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package book

import (
	"gf_demo/api/book"
)

type ControllerV1 struct{}

func NewV1() book.IBookV1 {
	return &ControllerV1{}
}
