// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package userinfo

import (
	"backend/api/userinfo"                      // api层的user包
	srvUser "backend/internal/service/userinfo" // service层的user包
	"backend/internal/service/userinfo/impl"
)

type ControllerV1 struct {
	// 用户信息服务
	svc srvUser.UserInfoService
}

// 这就是“注入 service 实现”：
// impl.New() 会返回一个对象，这个对象实现了 srvUser.UserInfoService
// 然后赋值给 controller 的 svc 字段
// 这样 Controller 就可以调用：c.svc.Create(ctx, &input)
func NewV1() userinfo.IUserinfoV1 {
	return &ControllerV1{
		svc: impl.New(),
	}
}
